//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _422_Tsyguleva_Pushkina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
        public decimal Num { get; set; }
        public decimal Price { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
